package streams;

import java.util.ArrayList;
import java.util.List;

public class TechData {
    public static ArrayList<String> data = new ArrayList<>(List.of(
            "--- PHASE 1: JAVA LANGUAGE & CORE INTERNALS (1-50) ---",
            "Java Primitive vs Wrapper Performance",
            "String Pool Internals & Interning",
            "Java Memory Model (JMM) Happens-Before Guarantee",
            "Java Memory Model (JMM) Variable Visibility",
            "Java Memory Model (JMM) Instruction Reordering",
            "Generics: Type Erasure Mechanics",
            "Generics: Covariance & Contravariance (PECS)",
            "Reflection API: Performance Overhead & Optimization",
            "Method Handles API (java.lang.invoke)",
            "Java Annotations: Retention Policies",
            "Annotation Processing Tool (APT) at Compile Time",
            "Java Modules (Project Jigsaw): Module-Path vs Class-Path",
            "Service Loader API in Modular Java",
            "Java 8: Lambda Expressions Internals (invokedynamic)",
            "Java 8: Stream API Pipeline Laziness",
            "Java 8: Optional Class Anti-patterns",
            "Java 8: CompletableFuture for Asynchronous Pipelines",
            "Java 9: Immutable Collection Factories",
            "Java 10: Local Variable Type Inference (var)",
            "Java 11: HTTP Client API (Reactive-based)",
            "Java 14: Switch Expressions (Yield/Arrows)",
            "Java 15: Text Blocks (Multi-line Strings)",
            "Java 16: Records (Data Carriers)",
            "Java 16: Pattern Matching for instanceof",
            "Java 17: Sealed Classes & Interfaces",
            "Java 21: Virtual Threads (Project Loom) Architecture",
            "Java 21: Structured Concurrency API",
            "Java 21: Scoped Values for Thread-local Data",
            "Java 21: Sequenced Collections",
            "Java 21: Pattern Matching for Switch",
            "Java 21: Record Patterns",
            "Dynamic Proxies (JDK vs CGLIB)",
            "Unsafe API: Memory Manipulation",
            "VarHandles for Atomic Operations",
            "Java Native Interface (JNI) Fundamentals",
            "Project Panama: Foreign Function & Memory API",
            "Serialization Vulnerabilities & Secure Coding",
            "Object Cloning: Shallow vs Deep Copy Mechanics",
            "Custom Class Loaders Implementation",
            "Class Loader Delegation Model",
            "Bytecode Manipulation (ASM, ByteBuddy)",
            "Java Agents (Instrumentation API)",
            "Reference Types: Weak, Soft, and Phantom References",
            "Cleaner API vs Finalizers",
            "IEEE 754 Floating Point Issues in Java",
            "BigDecimal for Financial Calculations",
            "Strictfp Keyword Usage",
            "Java Time API (JSR-310) Thread Safety",
            "Localization & Internationalization (I18N/L10N)",
            "SPI (Service Provider Interface) Pattern",

            "--- PHASE 2: JVM PERFORMANCE, GC & LOW-LEVEL TUNING (51-100) ---",
            "JVM Architecture: Stack vs Heap",
            "JVM Metaspace Management (PermGen Replacement)",
            "Code Cache Tuning for JIT",
            "JIT Compilation: C1 (Client) vs C2 (Server) Compilers",
            "Tiered Compilation Mechanics",
            "Inlining Optimization by JIT",
            "Escape Analysis & Scalar Replacement",
            "Intrinsics (Native Hardware Instructions)",
            "Garbage Collection: Serial GC Use Cases",
            "Garbage Collection: Parallel GC for Throughput",
            "Garbage Collection: CMS (Concurrent Mark Sweep) - Deprecated",
            "Garbage Collection: G1 GC (Garbage First) Regional Concepts",
            "G1 GC: Humongous Objects Handling",
            "G1 GC: Remembered Sets (RSets) and Collection Sets (CSets)",
            "ZGC (Z Garbage Collector): Sub-millisecond Pauses",
            "ZGC: Colored Pointers & Load Barriers",
            "Shenandoah GC: Concurrent Evacuation",
            "Epsilon GC: No-Op Collector for Testing",
            "JVM Safe Points & Stop-the-World Events",
            "Garbage Collection Logs Analysis (Xlog:gc)",
            "Heap Dump Analysis with Eclipse MAT",
            "Memory Leak Identification Patterns",
            "Thread Dump Analysis: Deadlocks & Starvation",
            "Flame Graphs for CPU Profiling",
            "JFR (JDK Flight Recorder) Event Streaming",
            "JMC (Java Mission Control) for Real-time Monitoring",
            "GraalVM Native Image Compilation",
            "Ahead-of-Time (AOT) Compilation",
            "PaaS JVM Tuning (Docker/K8s Resource Limits)",
            "NUMA-Aware JVM Tuning",
            "Compressed OOPs (Ordinary Object Pointers)",
            "Direct Memory Buffers (Off-heap Memory)",
            "Manual Memory Management with MappedByteBuffer",
            "CPU Cache Locality & False Sharing (Contended)",
            "JVM Intrinsic Candidate Identification",
            "String Deduplication in G1 GC",
            "Class Data Sharing (AppCDS) for Fast Startup",
            "Vector API for SIMD Operations",
            "Analyzing Bytecode with javap",
            "JIT Watch: Visualizing JIT Decisions",
            "Tuning JVM Stack Size (-Xss)",
            "Maximum Heap Size (-Xmx) vs Physical Memory",
            "Young Gen vs Old Gen Ratio Tuning",
            "Survivor Space & Tenuring Threshold Tuning",
            "Explicit GC (System.gc()) Risks",
            "JVM Options: -XX:+UnlockDiagnosticVMOptions",
            "JVM Options: -XX:+PrintFlagsFinal",
            "JVM Options: -XX:+HeapDumpOnOutOfMemoryError",
            "Monitoring JVM via JMX (Java Management Extensions)",
            "Serviceability Agent Internals",

            "--- PHASE 3: MULTITHREADING, CONCURRENCY & PARALLELISM (101-150) ---",
            "Thread Lifecycle & States",
            "Synchronized Block vs ReentrantLock",
            "Intrinsic Locks vs Explicit Locks",
            "ReadWriteLock for Optimized Reading",
            "StampedLock with Optimistic Reading",
            "Condition Objects for Thread Signaling",
            "Wait/Notify Pitfalls (Lost Signals, Spurious Wakeups)",
            "Atomic Variables (AtomicInteger, AtomicReference)",
            "LongAdder vs AtomicLong for High Contention",
            "CAS (Compare-and-Swap) Lock-free Algorithms",
            "Concurrent Collections: ConcurrentHashMap Internals",
            "Concurrent Collections: CopyOnWriteArrayList",
            "Concurrent Collections: ConcurrentLinkedQueue",
            "BlockingQueue Implementations (Array, Linked, Synchronous)",
            "TransferQueue (Java 7)",
            "CountDownLatch for One-time Sync",
            "CyclicBarrier for Reusable Sync",
            "Phaser: Flexible Multi-phase Sync",
            "Exchanger: Peer-to-Peer Data Swap",
            "Semaphore for Resource Throttling",
            "ExecutorService & Thread Pool Patterns",
            "ThreadPoolExecutor Customization",
            "ScheduledExecutorService for Periodic Tasks",
            "ForkJoinPool & Work-Stealing Algorithm",
            "RecursiveTask vs RecursiveAction",
            "Parallel Streams Performance Risks",
            "ThreadLocal Storage & Memory Leak Risks",
            "InheritableThreadLocal Mechanics",
            "InterruptedException Handling Best Practices",
            "Deadlock Detection & Prevention Strategies",
            "Livelock and Starvation Scenarios",
            "Double-Checked Locking Volatile Pattern",
            "Thread Groups (Deprecated) vs Thread Factories",
            "Virtual Thread Scheduling on Carrier Threads",
            "Pinning Issues in Virtual Threads",
            "Reactive Programming Flow API (Java 9)",
            "Blocking vs Non-blocking I/O",
            "Java NIO: Channels and Buffers",
            "Java NIO: Selectors and Multiplexing",
            "Asynchronous Socket Channels",
            "Disruptor Pattern (LMAX) for Ultra-low Latency",
            "Affinity Threads (Binding to CPU Cores)",
            "Ring Buffer Architectures",
            "Wait-free vs Lock-free Data Structures",
            "The ABA Problem in Concurrency",
            "Memory Barriers (LoadLoad, StoreStore, etc.)",
            "Hardware Transactional Memory (HTM)",
            "Software Transactional Memory (STM) Concepts",
            "Fiber vs Thread Performance Benchmarking",
            "Correct Use of volatile for Flags",

            "--- PHASE 4: EFFECTIVE DESIGN, PATTERNS & ARCHITECTURE (151-200) ---",
            "SOLID: Single Responsibility Deep Dive",
            "SOLID: Open/Closed (Extension vs Modification)",
            "SOLID: Liskov Substitution (Contract Compliance)",
            "SOLID: Interface Segregation (Lean Interfaces)",
            "SOLID: Dependency Inversion (Abstraction reliance)",
            "DRY (Don't Repeat Yourself) vs AHA (Avoid Hasty Abstraction)",
            "KISS (Keep It Simple, Stupid) Principle",
            "YAGNI (You Ain't Gonna Need It) Principle",
            "Composition over Inheritance",
            "Creational Patterns: Singleton (Thread-safe)",
            "Creational Patterns: Factory Method & Abstract Factory",
            "Creational Patterns: Builder (with Fluent API)",
            "Creational Patterns: Prototype & Registry",
            "Structural Patterns: Adapter & Bridge",
            "Structural Patterns: Composite (Tree Structures)",
            "Structural Patterns: Decorator (Wrapper)",
            "Structural Patterns: Facade (Simple Interface)",
            "Structural Patterns: Flyweight (Memory Saving)",
            "Structural Patterns: Proxy (Lazy/Remote/Security)",
            "Behavioral Patterns: Strategy (Algorithm Swap)",
            "Behavioral Patterns: Observer (Pub/Sub)",
            "Behavioral Patterns: State (FSM)",
            "Behavioral Patterns: Template Method",
            "Behavioral Patterns: Chain of Responsibility",
            "Behavioral Patterns: Command (Undo/Redo)",
            "Behavioral Patterns: Iterator & Visitor",
            "Behavioral Patterns: Memento (Snapshots)",
            "Behavioral Patterns: Mediator (Reduced Coupling)",
            "Domain-Driven Design: Ubiquitous Language",
            "DDD: Bounded Contexts & Context Mapping",
            "DDD: Aggregates, Entities, and Value Objects",
            "DDD: Domain Services vs Application Services",
            "DDD: Repositories vs DAOs",
            "DDD: Domain Events & Side Effects",
            "Hexagonal Architecture (Ports and Adapters)",
            "Clean Architecture (Onion/Screaming Architecture)",
            "Microkernel Architecture (Plugin-based)",
            "CQRS (Command Query Responsibility Segregation)",
            "Event Sourcing: Replaying State",
            "Anemic Domain Model vs Rich Domain Model",
            "Service Oriented Architecture (SOA) vs Microservices",
            "The 12-Factor App Methodology",
            "Stateless vs Stateful Design",
            "Anti-corruption Layers",
            "Idempotency in API Design",
            "Side-car Pattern for Cross-cutting Concerns",
            "Ambassador Pattern",
            "Strangler Fig Pattern for Legacy Migration",
            "Bulkhead Pattern for Fault Isolation",
            "Circuit Breaker Pattern (Fail Fast)",

            "--- PHASE 5: DATA ACCESS, HIBERNATE & DATABASES (201-251) ---",
            "JDBC Fundamentals & Statement Batching",
            "Connection Pooling (HikariCP, Druid, Tomcat)",
            "JPA (Java Persistence API) Entity Lifecycle",
            "Hibernate: Persistence Context & Session Management",
            "Hibernate: First-level Cache (Session Scope)",
            "Hibernate: Second-level Cache (Shared Scope)",
            "Hibernate: Query Cache Mechanics",
            "Hibernate: Lazy Loading vs Eager Fetching",
            "Hibernate: N+1 Select Problem Identification",
            "Hibernate: Join Fetching vs Entity Graphs",
            "Hibernate: Batch Fetching (@BatchSize)",
            "Hibernate: Dynamic Insert & Update",
            "Hibernate: Interceptors and Event Listeners",
            "Hibernate: Envers for Auditing",
            "Hibernate: Reactive (for Non-blocking SQL)",
            "Database Locking: Optimistic (Version Column)",
            "Database Locking: Pessimistic (SELECT FOR UPDATE)",
            "Transaction Isolation Levels (Read Uncommitted to Serializable)",
            "Transaction Propagation Behaviors (REQUIRED, REQUIRES_NEW, etc.)",
            "Declarative (@Transactional) vs Programmatic Transactions",
            "Spring Data JPA: Repository Abstraction",
            "Spring Data JPA: Query Methods & @Query",
            "Spring Data JPA: Specifications API for Dynamic Queries",
            "Spring Data JPA: Projections (Interface vs Class)",
            "Querydsl for Type-safe SQL Building",
            "JOOQ (Java Object Oriented Querying)",
            "MyBatis for Control over SQL",
            "Flyway: Version-based Migrations",
            "Liquibase: XML/YAML/JSON Database Changesets",
            "PostgreSQL: Index Types (B-Tree, GIN, GiST)",
            "PostgreSQL: Explain Analyze & Query Plans",
            "PostgreSQL: Partitioning Strategies",
            "PostgreSQL: JSONB for Semi-structured Data",
            "MySQL: InnoDB Storage Engine Internals",
            "MySQL: Buffer Pool Tuning",
            "NoSQL: MongoDB Document Modeling",
            "NoSQL: Cassandra Column Family & Partition Keys",
            "NoSQL: Redis Data Structures (Hashes, Sorted Sets, HyperLogLog)",
            "NoSQL: DynamoDB Design Patterns (GSI/LSI)",
            "Distributed Databases: Sharding Mechanics",
            "Distributed Databases: Replicas & Read/Write Splitting",
            "CAP Theorem: Consistency vs Availability vs Partition Tolerance",
            "PACELC Theorem: Beyond CAP",
            "BASE (Basically Available, Soft state, Eventual consistency)",
            "Distributed Transactions: Two-Phase Commit (2PC)",
            "Distributed Transactions: TCC (Try-Confirm-Cancel)",
            "Saga Pattern: Choreography-based",
            "Saga Pattern: Orchestration-based",
            "CDC (Change Data Capture) with Debezium",
            "Vector Databases (Milvus, Pinecone) for AI/LLM",
            "Time-Series Databases (InfluxDB, TimescaleDB)",

            "--- PHASE 6: SPRING FRAMEWORK & SPRING BOOT ECOSYSTEM (252-302) ---",
            "Spring Core: BeanFactory vs ApplicationContext",
            "Spring Core: Bean Scopes (Singleton, Prototype, Request, Session)",
            "Spring Core: Bean Post Processors",
            "Spring Core: Bean Factory Post Processors",
            "Spring Core: Circular Dependency Resolution",
            "Spring AOP: JDK Dynamic Proxy vs CGLIB",
            "Spring AOP: Pointcuts, Advice, and Aspects",
            "Spring SpEL (Expression Language) Security",
            "Spring Resources & ResourceLoader",
            "Spring Event Multi-casting (ApplicationEvent)",
            "Spring Boot: Auto-configuration Mechanics (@EnableAutoConfiguration)",
            "Spring Boot: Conditionals (@ConditionalOnProperty, etc.)",
            "Spring Boot: Custom Starters Development",
            "Spring Boot: Externalized Configuration (Priority Order)",
            "Spring Boot: Configuration Properties Validation",
            "Spring Boot: Actuator Custom Endpoints",
            "Spring Boot: Micrometer Integration",
            "Spring Boot: DevTools & LiveReload",
            "Spring Boot: Fat Jar vs Exploded Deployment",
            "Spring Boot: Layered Jars for Docker",
            "Spring MVC: DispatcherServlet Workflow",
            "Spring MVC: Content Negotiation (JSON, XML, Protobuf)",
            "Spring MVC: HandlerInterceptors vs Servlet Filters",
            "Spring MVC: Global Exception Handling (ControllerAdvice)",
            "Spring MVC: Async Request Processing",
            "Spring Security: Filter Chain Architecture",
            "Spring Security: AuthenticationManager & Providers",
            "Spring Security: UserDetailsService & PasswordEncoding",
            "Spring Security: Method Level Security (@PreAuthorize)",
            "Spring Security: OAuth2 Client & Resource Server",
            "Spring Security: OpenID Connect (OIDC) Integration",
            "Spring Security: JWT Authentication Flow",
            "Spring Security: CSRF & CORS Configuration",
            "Spring Security: Session Management & Hijacking Protection",
            "Spring Cloud: Config Server & Vault Integration",
            "Spring Cloud: Service Discovery (Eureka/Consul)",
            "Spring Cloud: Gateway (Predicates & Filters)",
            "Spring Cloud: Resilience4j Circuit Breaker/Rate Limiter",
            "Spring Cloud: OpenFeign for Declarative Clients",
            "Spring Cloud: Stream (Message-driven Microservices)",
            "Spring Cloud: Sleuth/Micrometer Tracing",
            "Spring WebFlux: Reactive Netty Server",
            "Spring WebFlux: Functional Endpoints vs Annotations",
            "Project Reactor: Operators (Map, FlatMap, SwitchIfEmpty, Zip)",
            "Project Reactor: Error Handling Strategies",
            "Project Reactor: Context Propagation",
            "Project Reactor: Schedulers & Threading Models",
            "Spring Batch: Chunk-oriented Processing",
            "Spring Batch: Readers, Processors, and Writers",
            "Spring Batch: Job Partitioning & Scaling",

            "--- PHASE 7: MESSAGING, EVENT-DRIVEN & STREAMING (303-353) ---",
            "Message Queue Fundamentals: Point-to-Point vs Pub/Sub",
            "RabbitMQ: Exchanges (Direct, Topic, Fanout, Headers)",
            "RabbitMQ: Queues, Bindings, and Routing Keys",
            "RabbitMQ: Acknowledgments & Negative Acks",
            "RabbitMQ: Dead Letter Exchanges (DLX)",
            "RabbitMQ: TTL and Priority Queues",
            "Apache Kafka: Topics, Partitions, and Segments",
            "Apache Kafka: Producer Acknowledgments (acks=all/1/0)",
            "Apache Kafka: Consumer Groups & Rebalancing",
            "Apache Kafka: Offset Management & Commitment",
            "Apache Kafka: Retention Policies & Compaction",
            "Apache Kafka: Zookeeper vs KRaft Mode",
            "Kafka Streams: State Stores & Windowing",
            "Kafka Connect: Source & Sink Connectors",
            "Kafka Schema Registry (Avro, Protobuf, JSON Schema)",
            "Exactly-once Processing (EOS) in Kafka",
            "Message Idempotency & De-duplication Patterns",
            "Outbox Pattern for Reliable Messaging",
            "Transactional Outbox with Debezium",
            "Competing Consumers Pattern",
            "Priority Queue Pattern",
            "Request-Reply over Messaging",
            "Cloud Events Specification",
            "Amazon SQS/SNS for Managed Messaging",
            "Azure Service Bus / Event Hubs",
            "Google Pub/Sub Mechanisms",
            "Apache Pulsar: Multi-tenancy & Tiered Storage",
            "Event Mesh Concepts",
            "AsyncAPI Specification",
            "Monitoring Message Lag",
            "Message Backpressure Handling",
            "Circuit Breakers in Message Consumers",
            "Poison Pill Handling",
            "Graceful Shutdown of Message Listeners",
            "Distributed Tracing through Message Headers",
            "Testing Messaging with Testcontainers",
            "Simulating Network Partitions in Clusters",
            "Log-structured Merge-trees (LSM) in Kafka",
            "Zero-copy Data Transfer in Kafka",
            "Consumer Interceptors",
            "Producer Interceptors",
            "Custom Partitioners in Kafka",
            "Dynamic Topic Creation Policies",
            "Security: SASL/PLAIN, SASL/SCRAM, Mutual TLS",
            "ACLs in Kafka Cluster",
            "Kafka Quotas for Multi-tenant Limits",
            "Tiered Storage in Kafka 3.x+",
            "MirrorMaker 2 for Cross-cluster Replication",
            "ActiveMQ Artemis Fundamentals",
            "MQTT for IoT Connectivity",
            "NATS for High-performance Cloud Native Messaging",

            "--- PHASE 8: API DESIGN, NETWORKING & WEB PROTOCOLS (354-404) ---",
            "REST: Maturity Model (Richardson Levels 0-3)",
            "REST: HATEOAS (Hypermedia as the Engine of Application State)",
            "REST: Resource Naming & URI Best Practices",
            "REST: HTTP Methods Semantics (Idempotent vs Safe)",
            "REST: Patch vs Put (Partial vs Full Update)",
            "API Versioning: URI, Header, and Media Type",
            "OpenAPI (Swagger) Specification 3.0/3.1",
            "JSON:API Standard",
            "gRPC: Protocol Buffers (proto3) Syntax",
            "gRPC: Unary, Server Streaming, Client Streaming, Bidirectional",
            "gRPC: Error Handling with Status Codes",
            "gRPC: Interceptors & Metadata",
            "GraphQL: Schema Definition Language (SDL)",
            "GraphQL: Queries, Mutations, and Subscriptions",
            "GraphQL: N+1 Problem & DataLoader Pattern",
            "GraphQL: Federations & Gateway (Apollo/Netflix DGS)",
            "WebSockets: Full-duplex Communication",
            "STOMP Protocol over WebSockets",
            "Server-Sent Events (SSE) for Unidirectional Push",
            "R Socket: Binary Reactive Protocol",
            "HTTP/1.1 vs HTTP/2 (Multiplexing, Binary, Header Compression)",
            "HTTP/3 & QUIC Protocol Fundamentals",
            "TLS/SSL Handshake Process",
            "mTLS (Mutual TLS) for Service-to-Service Auth",
            "OAuth2 Scopes vs Roles",
            "JWT: Header, Payload, Signature Security",
            "JWT: JWS (Signing) vs JWE (Encryption)",
            "JWT: Refresh Token Rotation Patterns",
            "CORS: Preflight Requests & Options Method",
            "Content Security Policy (CSP) Headers",
            "HSTS (HTTP Strict Transport Security)",
            "Rate Limiting: Token Bucket vs Leaky Bucket",
            "Rate Limiting: Fixed Window vs Sliding Log",
            "API Gateways: Authentication, Throttling, and Routing",
            "Backend for Frontends (BFF) Pattern",
            "Reverse Proxies: Nginx & HAProxy Config",
            "Load Balancing: Round Robin, Least Conn, IP Hash",
            "L4 (Transport) vs L7 (Application) Load Balancing",
            "DNS: A, AAAA, CNAME, TXT Records",
            "DNS: How Resolution Works (Recursive vs Iterative)",
            "IP Addressing: IPv4 vs IPv6",
            "TCP: Three-way Handshake & Flow Control",
            "UDP: Use Cases for Low Latency",
            "OSI Model: Layer 1 to Layer 7 Functions",
            "CDN (Content Delivery Network) Caching & Edge Computing",
            "Web Caching: ETag, Last-Modified, Cache-Control",
            "API Documentation with Redoc/Slate",
            "Testing APIs with RestAssured",
            "Mocking External APIs (WireMock, Prism)",
            "Contract Testing with Pact",

            "--- PHASE 9: CLOUD, DEVOPS, DOCKER & KUBERNETES (405-455) ---",
            "Docker: Image Layers & Union File System",
            "Docker: Multi-stage Builds for Lean Images",
            "Docker: Container Networking & Bridge Mode",
            "Docker: Volume Types & Data Persistence",
            "Docker: Compose for Local Orchestration",
            "Docker: Security Benchmarking (CIS)",
            "Kubernetes: Architecture (Control Plane vs Worker Nodes)",
            "Kubernetes: Pods, ReplicaSets, and Deployments",
            "Kubernetes: Services (ClusterIP, NodePort, LoadBalancer)",
            "Kubernetes: Ingress Controllers (Nginx, Traefik, ALB)",
            "Kubernetes: ConfigMaps & Secrets Management",
            "Kubernetes: Persistent Volumes (PV) & Claims (PVC)",
            "Kubernetes: Liveness, Readiness, and Startup Probes",
            "Kubernetes: Resource Quotas & Limit Ranges",
            "Kubernetes: Horizontal Pod Autoscaler (HPA)",
            "Kubernetes: Vertical Pod Autoscaler (VPA)",
            "Kubernetes: Taints, Tolerations, and Node Affinity",
            "Kubernetes: Jobs & CronJobs",
            "Kubernetes: StatefulSets for Databases",
            "Helm: Charts, Templates, and Value Files",
            "Helm: Release Management & Rollbacks",
            "Kustomize: Declarative Config Management",
            "Service Mesh: Istio Envoy Proxy",
            "Service Mesh: Traffic Splitting & Canary Deployment",
            "Service Mesh: Mutual TLS & Security Policy",
            "Service Mesh: Observability with Kiali",
            "CI/CD: GitHub Actions Workflows",
            "CI/CD: GitLab CI Runners",
            "CI/CD: Jenkins Pipelines (Groovy DSL)",
            "CI/CD: Deployment Strategies (Blue-Green, Canary, Recreate)",
            "Infrastructure as Code (IaC): Terraform Providers & Modules",
            "Terraform State Management & Locking",
            "Ansible Playbooks for Server Configuration",
            "Cloud: AWS EC2, S3, and RDS Essentials",
            "Cloud: AWS IAM Roles & Policies",
            "Cloud: AWS Lambda (Serverless Java with SnapStart)",
            "Cloud: Azure App Service & CosmosDB",
            "Cloud: GCP Cloud Run & Spanner",
            "Cloud Native Buildpacks",
            "Logging: ELK Stack (Elasticsearch, Logstash, Kibana)",
            "Logging: EFK Stack (Fluentd instead of Logstash)",
            "Logging: Grafana Loki for Log Aggregation",
            "Metrics: Prometheus Data Model & PromQL",
            "Metrics: Grafana Dashboards for JVM Monitoring",
            "Tracing: Jaeger & Zipkin Distributed Tracing",
            "OpenTelemetry (OTel) Collector & Instrumentation",
            "SRE: Error Budgets & SLOs/SLIs",
            "Chaos Engineering: Chaos Monkey & Gremlin",
            "GitOps: ArgoCD or FluxCD for K8s",
            "Secrets Management: HashiCorp Vault",

            "--- PHASE 10: TESTING, SECURITY & SENIOR LEADERSHIP (456-505) ---",
            "Unit Testing: JUnit 5 Jupiter Extension Model",
            "Unit Testing: TDD (Test Driven Development) Cycles",
            "Mocking: Mockito Deep Mocks vs Spies",
            "Mocking: BDDMockito Style (Given/When/Then)",
            "Assertion: AssertJ Fluent API",
            "Integration Testing: Testcontainers for DBs & Queues",
            "Integration Testing: SpringBootTest Context Caching",
            "Performance Testing: JMeter for Load Testing",
            "Performance Testing: Gatling (Scala/Java DSL)",
            "Performance Testing: k6 (JS/Go-based)",
            "Mutation Testing: Pitest (Testing your Tests)",
            "Consumer-Driven Contract Testing (Pact)",
            "Architecture Testing with ArchUnit",
            "Security: OWASP Top 10 Vulnerabilities",
            "Security: SQL Injection & XSS Mitigation",
            "Security: Dependency Scanning (Snyk, Dependency-Check)",
            "Security: Static Application Security Testing (SAST - SonarQube)",
            "Security: Dynamic Application Security Testing (DAST)",
            "Security: Secrets in Source Code Detection (Gitleaks)",
            "Security: Cryptography (AES, RSA, ECC in Java)",
            "Security: Hashing Algorithms (BCrypt, Argon2)",
            "Build Tools: Maven Lifecycle & Plugin Development",
            "Build Tools: Maven Bill of Materials (BOM)",
            "Build Tools: Gradle Kotlin DSL vs Groovy",
            "Build Tools: Gradle Build Cache & Incremental Builds",
            "Code Quality: Static Analysis (Checkstyle, PMD, SpotBugs)",
            "Code Quality: Cognitive Complexity Metrics",
            "Agile: Scrum vs Kanban vs Scrumban",
            "Agile: Story Pointing & Velocity",
            "Architecture Decision Records (ADR)",
            "Technical Debt Management Strategies",
            "Refactoring Legacy Code (Feathers Approach)",
            "Documentation: C4 Model for Software Architecture",
            "Documentation: Technical Writing for Engineers",
            "Mentoring: Code Review Best Practices",
            "Mentoring: Pair Programming Techniques",
            "Leadership: Leading Technical Design Reviews",
            "Leadership: Influencing without Authority",
            "Leadership: Conflict Resolution in Tech Teams",
            "System Design: Designing for High Availability (99.999%)",
            "System Design: Designing for Scalability (Millions of RPS)",
            "System Design: Disaster Recovery (RPO/RTO)",
            "System Design: Multi-region Active-Active Architecture",
            "System Design: Database Migration without Downtime",
            "System Design: Handling Hotkeys in Distributed Caches",
            "System Design: Backpressure & Load Shedding",
            "Career: Building a Technical Portfolio",
            "Career: Contributing to Open Source",
            "Career: Public Speaking & Tech Blogging",
            "Career: Transitioning to Staff/Principal Engineer"));

}
